apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pets-pvc","namespace":"kubeflow"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"nfs"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-server-provisioner
  creationTimestamp: "2020-02-05T21:22:10Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pets-pvc
  namespace: kubeflow
  resourceVersion: "38683951"
  selfLink: /api/v1/namespaces/kubeflow/persistentvolumeclaims/pets-pvc
  uid: 91c60318-485d-11ea-8b0c-42010a800067
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: pvc-91c60318-485d-11ea-8b0c-42010a800067
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  phase: Bound
